

import Image from 'next/image'
import getConfig from 'next/config'
const {publicRuntimeConfig } = getConfig()

export default function Contract({pageInfo}) {
    return (
<div className="el-pdf-doc" >
     <div className="col-12 px-3">

    <h4><strong>Representation Agreement</strong></h4>

    <p>I, <strong>{pageInfo.clientName}</strong> (hereafter referred to as "Client"), hereby apply for the legal representation services of OAK VIEW LAW GROUP, APC (hereafter referred to as "OVLG").</p>

    <p>Client understands that he/she has (or may have) the following options in handling their debts: (a) doing nothing; (b) filing for Chapter 7, which will entail the Client losing assets in order to repay the majority, but not all of their debts ; (c) filing Chapter 13 Bankruptcy, where client will make payments to a court appointed trustee for a period of 3 to 5 years, after which he/she will not have to pay anything further towards his/her debts; (d) debt settlement where OVLG will attempt to negotiate a lower principal amount and interest rates on Client's debts; and (e) debt management where all of Client's debts will be paid at a reduced interest rate. </p>

    <p>Client has chosen debt settlement because Client desires to pay what he/she can afford, on his/her debt, but after evaluation of their financial situation by OVLG, agrees that they cannot afford to repay entire amount. Client also understands that the debt settlement program typically takes between 6 months to 4 years.</p>

    <p> <strong>SERVICES :</strong> Client understands that if he/she is accepted for OVLG's debt settlement services, OVLG will contact his/her creditors, request them to contact OVLG rather than the client, and attempt to reach a satisfactory settlement or payment plan with his/her creditor(s). Client also understands that at least 30% of the debt amount per creditor needs to be accumulated in his/her trust account before OVLG will make a settlement offer to the creditor. OVLG will only be working on the accounts the client requested them to work upon along with any other additional accounts added while he/she is still in the program. Client authorizes OVLG to delegate any portion of the services provided to any attorneys or non-attorneys it chooses, to be performed in any matter, and any location OVLG deems appropriate. </p>

    <p><strong> FEES :</strong>For this service, client will pay:</p>

    <p><strong>A. A consultancy</strong>  of $50 be charged each month fee  of $50 will  be charged each month for  providing a a monthly  30 minutes  consultation  with  our  savings providing consultants, 30 minutes consultation with budgeting consultant and 30  minutes   consultation with   tax attorney.  This   fee  will  be and adjusted success completion of program. adjusted with  success  fee on  completion of program. For For example, if client $1000 as success fee and example, if client owes  $1000 as success fee and  total consultancy fee completion program $600 then the consultancy fee on  completion of  program is  $600 then the client has to pay only $400 towards success fee ($1000-$600). </p>

    <p><strong>B. A fee of of 15% </strong> of of the   debt  amount  will be  charged as  a success  fee. For example, if client owes $10,000 on  an account and OVLG negotiates negotiates a a reduction reduction  on that that account account to to $6,000, $6,000, saving saving OVLG Client $4,000, then then OVLG's OVLG's success  fee for  that account is 15% Client of $10,000, i.e. $1500. While  calculating the success fee, it will of assumed amount owed account is the be assumed  that the amount owed on any account is the amount owed owed  by the client at the  time of enrollment in  OVLG's amount debt settlement program. reduced debt settlement program. This fee will be reduced by the amount of consultant fee already paid by the client.</p>
    <p><strong>MONTHLY PAYMENTS : </strong>Client will make payments in the amount mentioned in the ACH form that Client has signed and is attached to this agreement. From this payment, OVLG will take $50 per month as its consultation as stated in Fees section A above. </p>

    <p><strong>ESTIMATED COST OF SETTLING : </strong>OVLG estimates that all of Client's accounts can be settled in full if Client sets aside a total of $____ over a period of ___ months. OVLG bases these estimates on industry trends and its experience, but stresses that these are ESTIMATES only, not guarantees. The length of time and amount of money necessary to settle Client's debts is an estimate only, which can change depending on the amount Client is able to set-aside, and possible changes in the industry and settlement policies of Client's creditors.</p>

    <p><strong>CREDITOR SET-ASIDES : </strong>Client will not be making any periodic payments or deposits to creditors. Instead, Client will set aside funds, as Client is able to do so, and may leave or put these funds into any existing or new account that Client chooses. Client may (but is not required to) deposit funds into a bank account recommended by OVLG. If Client elects to do so, that will be at Client's sole discretion, and Client will not be required to make any specific deposits at any time. Wherever Client chooses to accumulate the funds to be paid to creditors, Client will let OVLG know the amount of funds available. OVLG will then endeavor to obtain settlement proposals from Creditors that are consistent with Client's ability to pay, and transmit these offers to Client. OVLG may make recommendations regarding these proposals to Creditors, but the amount Client pays to any Creditor, and whether Client accepts any of these offers, is the final decision of Client. Client understands that OVLG will not distribute, supervise, coordinate, or control the distribution of any of Client's funds to Creditors.</p>

    <p><strong>NO PRACTICE OF LAW IN CLIENT'S STATE OF RESIDENCE : </strong>Client understands that OVLG employs attorneys licensed in California and (few other states) and that OVLG may not currently employ attorneys licensed in Client's state of residence. Thus, OVLG will not be engaging in the practice of law in Client's state of residence. OVLG will provide general information to Client regarding Client's rights and options under Federal statutes, such as the Fair Debt Collection Practices Act, the Fair Credit Reporting Act, the Federal Trade Commission Act, and the U.S. Bankruptcy Code. OVLG will not provide any advice to client concerning laws specific to Client's state of residence unless it is from an attorney licensed in Client's state of residence. Client understands and has been informed that, according to the best of OVLG's information and research, the activities to be undertaken by OVLG pursuant to this agreement are not deemed to be the practice of law in Client's state of residence. In the event that such activities become deemed to be the practice of law in Client's state of residence, then OVLG will hire an attorney licensed in Client's state of residence who will be responsible for client's case, or if unable to do so, will refund the fees paid by Client.</p>

    <p><strong>LAWSUITS :</strong>In the event that a lawsuit is filed against Client, OVLG will attempt to negotiate a settlement and/or payment arrangement acceptable to Client, and if that is not possible, then OVLG will explain the other options available to Client. Client is not hiring OVLG to represent him/her in any lawsuit, file or prepare any documents for him/her to file in court, or attend any court hearings. If Client wants OVLG to represent him/her or provide further assistance in any court proceeding, there will be additional fees involved.</p>

    <p><strong>BANKRUPTCY : </strong>OVLG's fee for a Chapter 7 will be $1,800, and for a Chapter 13, $3,000 down, plus the remaining fees to be set by the court and paid through the court appointed trustee. </p>

    <p><strong>NO GUARANTEE :</strong> Client understands that not all creditors or debt collectors will accept a reduction in the balance, interest rate, or fees that Client owes to them. So, there can be no guarantee that any particular creditor, or Client's creditors as a whole, will settle for any particular amount. OVLG has based all estimates on industry trends and its experience, but stresses these are projected estimates, not guarantees. The length of time to settle Client's debts and the number of payments needed to make a settlement of all accounts is an estimate only, and can change according to timeliness of Client set- asides and possible changes in creditor's settlement policies.</p>

    <p><strong>ACCOUNT DELINQUENCY : </strong>Client understands that his/her accounts will become delinquent during the settlement program, and unless the accounts become delinquent it is unlikely that any settlement for a substantial savings will occur. Client also understands that creditors may raise interest rates while Client is in this program, and that late fees, penalties, and interest will continue to accrue on Client's debts until a settlement offer has been made, accepted, and paid.</p>

    <p><strong>CREDITOR HARASSMENT : </strong>Client understands that while the completion of the represented debt-relief services is still pending, Client's creditors or debt collectors may pursue collection efforts, including initiation of lawsuits. Client may continue to receive phone calls from creditors even after OVLG has notified the creditors not to contact Client. Client agrees to keep a log, in the "Secure client area" on OVLG's website, of contacts by creditors, including the name and phone number of the calling creditor, the date and time of the call, and a brief summary of the conversation and forward this log to OVLG in a timely manner as evidence so OVLG may address the situation accordingly.</p>

    <p><strong>TIMING OF SETTLEMENTS : </strong>Client understands that a settlement will not be reached with a creditor until Client has accumulated enough funds to make a lump sum payoff in accordance with this agreement.</p>
    <p><strong>TAX CONSEQUENCES : </strong>Client understands that savings realized from the use of a debt-relief service may be taxable income. Client may be liable for federal and state taxes in the amount of the debt forgiven by Client's creditors. Therefore, the use of the debt-relief service is likely to affect Client's creditworthiness adversely, may result in being sued by Client's creditors, and may increase the amount owed to creditors as a result of the accrued interest and additional fees.</p>

    <p><strong>CREDIT RATING : </strong>Client has not hired OVLG to provide any "Credit Repair" services. Client acknowledges that a debt settlement may result in derogatory credit information being transmitted to the credit reporting agencies by Client's creditors. Once the debt is settled, Client's credit report will show "settled for less than full amount," "paid as agreed," or "paid settled". Client has hired OVLG solely to settle Client's debts, not to improve his/her credit rating.</p>

    <p><strong>FEES IN CASE OF DROPOUT : </strong>Client can stop working with OVLG without any penalty. The Trust Account balance will be refunded within 7 business days (minus any fees OVLG has earned).</p>
    <p><strong>100% MONEY BACK DUE TO DISSATISFACTION : </strong>For Oak View Law Group, clients come first. If for any reason Client is not satisfied with OVLG's services, Client should send a fax to OVLG President, attention "Mr. Virendra Kalani" at 800-637-6854, and tell OVLG why Client is unhappy with OVLG's services. If OVLG cannot help Client, OVLG will refund 100% of Client's fees within 7 business days.</p>

    <p><strong>START DATE OF SERVICES :</strong> In order to ensure timely attorney approval, the documents must be signed and faxed back to OVLG within 72 hours of receipt. The start date of the services is the date when the first payment is received.</p>
    <p><strong>ARBITRATION AND VENUE : </strong>Any dispute concerning the services referred to in this agreement shall be resolved in accordance with the laws of the State of California, and will be settled by arbitration in accordance with the rules of the American Arbitration Association. All such proceedings will take place in Santa Clara County, California, or, at Client's election, in Client's county of residence. Any award rendered by the arbitrator will be binding upon each of the parties and is not appealable. Any court of competent jurisdiction can confirm and enforce any arbitration award.<strong> By entering into this contract both parties are waiving their constitutional right to have any dispute decided in a Court of Law before a judge or jury, and instead are accepting arbitration as their exclusive method for the resolution of disputes.</strong></p>

    <p><strong>CLASS ACTION WAIVER : </strong>Client and OVLG may only bring claims against each other in an individual capacity and not as a class representative or a class member in a class or representative action. </p>

    <p><strong>ENFORCEABILITY : </strong>Client understands that OVLG has exercised its best efforts to ensure that this agreement complies with all applicable state and federal laws as of the date entered into. There is always the possibility, however, that new laws will be enacted, or that new interpretations will be made of existing laws. If any provision of this agreement is determined by any court, bar association, or other governmental agency to be contrary to applicable laws or rules, then such provision shall be interpreted so as to best accomplish the objectives of the original provision to the fullest extent allowed by law and Client will cooperate with OVLG in amending this Agreement so that its provisions are consistent with such laws, rules, and regulations.</p>

    <p><strong>TERMINATION : </strong>Client understands that he/she may terminate this agreement at any time by giving a written notice, and OVLG may terminate this agreement upon 30 days' written notice for Client's failure to cooperate or provide accurate and necessary information on a timely basis, failure to pay any fees OVLG is entitled to under this contract, failure to set aside sufficient funds to make settlements to creditors, and for other good and reasonable cause. If this legal representation agreement is terminated by OVLG, OVLG will return all the funds in Client's trust account.</p>

    <p><strong>MISCELLANEOUS : </strong>OVLG can use any written or video Testimonial received from Client for the marketing of OVLG and its services.</p> 

    <p><strong>PRIOR AGREEMENTS :</strong>Both parties understand and agree that this agreement shall constitute the entire agreement between Client and OVLG and supersedes all prior agreements. </p>

</div>
</div>
    )
  }



