export const calculatorList = [
  {
    "id": 1,
    "name": "debt-payoff calculator",
    "url": "https://www.ovlg.com/calculators/debt-payoff.html",
    "meta_tags": {
      "title": "Debt payoff calculator - How much time and money can you save?",
      "keywords": "debt pay off calculator, free online debt payoff calculator, debt repayment calculator, debt payoff method",
      "description": "Use this free online debt payoff calculator to see how quickly you can pay off debt. Find out how much you can save with the right debt payoff method.",
    },
    "templateFile": "debt-payoff",
    "url_alias": 'debt-payoff.html',
    "BannerInfo": { "pageTopicTitle": 'Debt-Payoff Calculator', },
    "FooterInfoBkp": { "excludeJs": ['jquery', 'bootstrap', 'global'] },
    "FooterInfo": { "excludeJs": ['jquery', 'bootstrap', 'global'] },
    "JsFlag": '1',
  },
  {
    "id": 2,
    "name": "debt-to-income ratio calculator",
    "url": "https://www.ovlg.com/calculators/debt-income-ratio.html",
    "meta_tags": {
      "title": "Debt to income ratio calculator - Calculate and reduce your DTI",
      "keywords": "debt-to-income ratio, debt-to-income ratio calculator, DTI ratio, front-end ratio",
      "description": "With the free debt to income ratio calculator, you can calculate your front-end and back-end ratio. Find out a debt solution to reduce your DTI.",
    },
    "templateFile": "debt-income-ratio",
    "url_alias": 'debt-income-ratio.html',
    "BannerInfo": { "pageTopicTitle": 'Debt to Income Ratio Calculator', },
    "FooterInfo": { "excludeJs": ['jquery', 'bootstrap', 'global'] },
  },
  {
    "id": 3,
    "name": "debt consolidation calculator",
    "url": "https://www.ovlg.com/calculators/debt-consolidation-types.html",
    "meta_tags": {
      "title": "Sample for debt settlement, validation, creditors, and credit bureaus",
      "keywords": "debt consolidation calculator",
      "description": "The debt consolidation calculator helps you find your best-fitted debt consolidation option by comparing all available debt consolidation options.",
    },
    "templateFile": "debt-consolidation-types",
    "url_alias": 'debt-consolidation-types.html',
    "BannerInfo": { "pageTopicTitle": 'Debt Consolidation Calculator', },
    "FooterInfo": { "excludeJs": ['jquery', 'bootstrap', 'global'] },
  },
  {
    "id": 4,
    "name": "APR Calculator",
    "url": "https://www.ovlg.com/calculators/apr-calculator.html",
    "meta_tags": {
      "title": "APR Calculators",
      "keywords": "APR, APR calculator, interest payments, credit card, credit score, credit card companies",
      "description": "Are you taking out a loan? Use our loan APR calculator to know your monthly payments and find out the true cost of borrowing a loan and compare loan offers.",
    },
    "templateFile": "apr-calculator",
    "url_alias": 'apr-calculator.html',
    "BannerInfo": { "pageTopicTitle": 'APR Calculator', },
    "FooterInfo": { "excludeJs": ['jquery', 'bootstrap', 'global'] },
  },
  {
    "id": 5,
    "name": "Credit Card Payoff Calculator",
    "url": "https://www.ovlg.com/calculators/credit-card-payment.html",
    "meta_tags": {
      "title": "Credit Card Payment Calculator",
      "keywords": "credit card payment calculator",
      "description": "Credit Card Payoff Calculator helps you analyze the interest and how long it would take to be debt-free when you have multiple credit card debts. Check out now!",
    },
    "templateFile": "credit-card-payment",
    "url_alias": 'credit-card-payment.html',
    "BannerInfo": { "pageTopicTitle": 'Credit Card Payoff Calculator', },
    "FooterInfo": { "excludeJs": ['jquery', 'bootstrap', 'global'] },
  },

]