export const letterList = [
  {
    "id": 1,
    "name": "Debt settlement offer in response to creditor's proposal",
    "url": "https://www.ovlg.com/letters/debt-settlement-offer.html",
    "meta_tags": {
      "title": "Debt settlement offer in response to creditor's proposal -OVLG",
      "keywords": "debt settlement offer letter",
      "description": "Not sure about how to counter your creditor’s debt settlement offer? Download this free Debt Settlement Offer Letter sample.",
    },
    "templateFile": "debt-settlement-offer",
    "url_alias": 'debt-settlement-offer.html',
  },
  {
    "id": 2,
    "name": "Letter confirming acceptance of a verbal offer",
    "url": "https://www.ovlg.com/letters/acceptance-of-verbal-offer.html",
    "meta_tags": {
      "title": "Letter confirming acceptance of a verbal offer -OVLG",
      "keywords": "verbal offer acceptance letter",
      "description": "Want to write a letter to your creditor confirming acceptance of a verbal offer? Download a free sample template of the debt settlement offer acceptance letter.",
    },
    "templateFile": "acceptance-of-verbal-offer",
    "url_alias": 'acceptance-of-verbal-offer.html',
  },
  {
    "id": 3,
    "name": "Sample letter for an unsolicited debt settlement offer",
    "url": "https://www.ovlg.com/letters/unsolicited-debt-settlement-offer.html",
    "meta_tags": {
      "title": "Sample letter for an unsolicited debt settlement offer -OVLG",
      "keywords": "unsolicited debt settlement letter",
      "description": "Know how to deal with an unsolicited debt settlement offer from your creditors. Download this free letter template today!",
    },
    "templateFile": "unsolicited-debt-settlement-offer",
    "url_alias": 'unsolicited-debt-settlement-offer.html',
  },
  {
    "id": 4,
    "name": "Letter for debt settlement agreement",
    "url": "https://www.ovlg.com/letters/debt-settlement-agreement.html",
    "meta_tags": {
      "title": "Letter for debt settlement agreement -OVLG",
      "keywords": "debt settlement agreement letter",
      "description": "Download this free sample of the debt settlement agreement template and know how to confirm the verbal debt settlement agreement in writing.",
    },
    "templateFile": "debt-settlement-agreement",
    "url_alias": 'debt-settlement-agreement.html',
  },
  {
    "id": 5,
    "name": "Pay for deletion agreement",
    "url": "https://www.ovlg.com/letters/pay-for-delete-letter.html",
    "meta_tags": {
      "title": "Pay for deletion agreement -OVLG",
      "keywords": "pay for delete letter",
      "description": "Free sample template of pay for delete agreement letter to help you negotiate a Pay for Delete Agreement with your creditor/collection agency. Download Now!",
    },
    "templateFile": "pay-for-delete-letter",
    "url_alias": 'pay-for-delete-letter.html',
  },
  {
    "id": 6,
    "name": "Cease and desist letter",
    "url": "https://www.ovlg.com/letters/cease-and-desist-letter.html",
    "meta_tags": {
      "title": "Cease and desist letter -OVLG",
      "keywords": "cease and desist letter",
      "description": "Free sample template of a Cease and Desist Letter to help you fight against the harassment made by debt collectors. Download Now!",
    },
    "templateFile": "cease-and-desist-letter",
    "url_alias": 'cease-and-desist-letter.html',
  },
  {
    "id": 7,
    "name": "Debt validation letter",
    "url": "https://www.ovlg.com/letters/debt-validation-letter.html",
    "meta_tags": {
      "title": "Debt validation letter -OVLG",
      "keywords": "debt validation letter",
      "description": "Download the free sample debt validation letter and request your creditor/collection agency in writing to validate your debt before you pay.",
    },
    "templateFile": "debt-validation-letter",
    "url_alias": 'debt-validation-letter.html',
  },
  {
    "id": 8,
    "name": "Expired SOL notification letter",
    "url": "https://www.ovlg.com/letters/expired-sol-notification-letter.html",
    "meta_tags": {
      "title": "Expired SOL notification letter -OVLG",
      "keywords": "",
      "description": "",
    },
    "templateFile": "expired-sol-notification-letter",
    "url_alias": 'expired-sol-notification-letter.html',
  },
  {
    "id": 9,
    "name": "Debt Collection Dispute Followup Letter",
    "url": "https://www.ovlg.com/letters/debt-collection-dispute.html",
    "meta_tags": {
      "title": "Debt Collection Dispute Followup Letter -OVLG",
      "keywords": "debt collection dispute letter",
      "description": "Download a free sample of the Debt Collection Dispute Follow-up Letter and follow up with your creditor/collection agency regarding your debt validation.",
    },
    "templateFile": "debt-collection-dispute",
    "url_alias": 'debt-collection-dispute.html',
  },
  {
    "id": 10,
    "name": "Debt verification letter",
    "url": "https://www.ovlg.com/letters/debt-verification-letter.html",
    "meta_tags": {
      "title": "Debt verification letter -OVLG",
      "keywords": "debt verification letter",
      "description": "Free sample of Debt verification letter to help you get your debts verified from your creditors. Download now!",
    },
    "templateFile": "debt-verification-letter",
    "url_alias": 'debt-verification-letter.html',
  },
  {
    "id": 11,
    "name": "Request to stop debt collection letter",
    "url": "https://www.ovlg.com/letters/stop-debt-collection.html",
    "meta_tags": {
      "title": "Request to stop debt collection letter -OVLG",
      "keywords": "",
      "description": "Download a free sample template of the Request to stop debt collection letter and request the collection agency in writing to stop contacting you.",
    },
    "templateFile": "stop-debt-collection",
    "url_alias": 'stop-debt-collection.html',
  },
  {
    "id": 12,
    "name": "Letter to correct disputing account status with the creditor",
    "url": "https://www.ovlg.com/letters/disputing-account-status.html",
    "meta_tags": {
      "title": "Letter to correct disputing account status with the creditor -OVLG",
      "keywords": "account dispute letter",
      "description": "Found an inaccurate listing on your credit report? Notify the credit bureaus by using this free sample letter to correct disputing account status. ",
    },
    "templateFile": "disputing-account-status",
    "url_alias": 'disputing-account-status.html',
  },
  {
    "id": 13,
    "name": "Request for debt re-verification letter",
    "url": "https://www.ovlg.com/letters/debt-re-verification.html",
    "meta_tags": {
      "title": "Request for debt re-verification letter -OVLG",
      "keywords": "debt reverification letter",
      "description": "Download a free sample of the Request for debt re-verification letter to deal with credit bureaus for a disputed item on your verified credit report.",
    },
    "templateFile": "debt-re-verification",
    "url_alias": 'debt-re-verification.html',
  },
  {
    "id": 14,
    "name": "Follow up letter to credit bureau",
    "url": "https://www.ovlg.com/letters/credit-bureau.html",
    "meta_tags": {
      "title": "Follow up letter to credit bureau -OVLG",
      "keywords": "credit bureau follow up letter",
      "description": "Failed to get a response from your credit bureau after the initial contact? Download the free sample of the follow-up letter and send a follow-up.",
    },
    "templateFile": "credit-bureau",
    "url_alias": 'credit-bureau.html',
  },
  {
    "id": 15,
    "name": "Request to remove inaccurate information from your credit report",
    "url": "https://www.ovlg.com/letters/inaccurate-credit-report.html",
    "meta_tags": {
      "title": "Request to remove inaccurate information from your credit report -OVLG",
      "keywords": "letter to remove information from credit report",
      "description": "Is your credit report showing inaccurate information that you need to remove? Request the credit bureaus by using this free sample letter. Download Now!",
    },
    "templateFile": "inaccurate-credit-report",
    "url_alias": 'inaccurate-credit-report.html',
  },
  {
    "id": 16,
    "name": "Goodwill letter",
    "url": "https://www.ovlg.com/letters/goodwill-letter.html",
    "meta_tags": {
      "title": "Goodwill letter -OVLG",
      "keywords": "goodwill letter",
      "description": "Download the free sample Goodwill letter and send a request to the creditor/collection agency for removing the old negative listing from your credit report.",
    },
    "templateFile": "goodwill-letter",
    "url_alias": 'goodwill-letter.html',
  },
  {
    "id": 17,
    "name": "Letter to request a reduced payment plan from a creditor",
    "url": "https://www.ovlg.com/letters/reduced-payment-plan.html",
    "meta_tags": {
      "title": "Letter to request a reduced payment plan from a creditor -OVLG",
      "keywords": "reduced payment plan letter",
      "description": "Struggling to make monthly payments on your debts? Know what to write to your creditor when requesting a reduced payment plan. Download the free Template!",
    },
    "templateFile": "reduced-payment-plan",
    "url_alias": 'reduced-payment-plan.html',
  },
  {
    "id": 18,
    "name": "Letter to revoke wage assignment request",
    "url": "https://www.ovlg.com/letters/revoke-wage-assignment.html",
    "meta_tags": {
      "title": "Letter to revoke wage assignment request -OVLG",
      "keywords": "Revoke Wage Assignment Letter",
      "description": "Free sample template of the Revoke Wage Assignment Letter to help you revoke the creditor's right of using the wage assignment for your debt payment.",
    },
    "templateFile": "revoke-wage-assignment",
    "url_alias": 'revoke-wage-assignment.html',
  },
  {
    "id": 19,
    "name": "Request removal of inquiries from credit report",
    "url": "https://www.ovlg.com/letters/removal-of-inquiries.html",
    "meta_tags": {
      "title": "Request removal of inquiries from credit report -OVLG",
      "keywords": "inquiry removal report",
      "description": "Know what to write when requesting your creditor for an inquiry removal from your credit report. Download the free sample template Now!",
    },
    "templateFile": "removal-of-inquiries",
    "url_alias": 'removal-of-inquiries.html',
  },
  {
    "id": 20,
    "name": "Letter to request an alternative payment plan from a creditor",
    "url": "https://www.ovlg.com/letters/alternative-payment-plan.html",
    "meta_tags": {
      "title": "Letter to request an alternative payment plan from a creditor -OVLG",
      "keywords": "alternate payment plan request letter",
      "description": "Have you become delinquent on your payments? Know how to request your creditors for an alternative payment plan. Download the free sample template now!",
    },
    "templateFile": "alternative-payment-plan",
    "url_alias": 'alternative-payment-plan.html',
  },
  {
    "id": 6,
    "name": "",
    "url": "https://www.ovlg.com/letters/",
    "meta_tags": {
      "title": " -OVLG",
      "keywords": "",
      "description": "",
    },
    "templateFile": "",
    "url_alias": '',
  },
]
